`ifndef DEFINE_STATE



// for top state - we have more states than needed
typedef enum logic [1:0] {
	S_IDLE,
	S_UART_RX,
	S_M1,	
	S_M2
} top_state_type;


typedef enum logic [1:0] {
	S_RXC_IDLE,
	S_RXC_SYNC,
	S_RXC_ASSEMBLE_DATA,
	S_RXC_STOP_BIT
} RX_Controller_state_type;

typedef enum logic [2:0] {
	S_US_IDLE,
	S_US_STRIP_FILE_HEADER_1,
	S_US_STRIP_FILE_HEADER_2,
	S_US_START_FIRST_BYTE_RECEIVE,
	S_US_WRITE_FIRST_BYTE,
	S_US_START_SECOND_BYTE_RECEIVE,
	S_US_WRITE_SECOND_BYTE
} UART_SRAM_state_type;



typedef enum logic [3:0] {
	S_VS_WAIT_NEW_PIXEL_ROW,
	S_VS_NEW_PIXEL_ROW_DELAY_1,
	S_VS_NEW_PIXEL_ROW_DELAY_2,
	S_VS_NEW_PIXEL_ROW_DELAY_3,
	S_VS_NEW_PIXEL_ROW_DELAY_4,
	S_VS_NEW_PIXEL_ROW_DELAY_5,
	S_VS_FETCH_PIXEL_DATA_0,
	S_VS_FETCH_PIXEL_DATA_1,
	S_VS_FETCH_PIXEL_DATA_2,
	S_VS_FETCH_PIXEL_DATA_3
} VGA_SRAM_state_type;

typedef enum logic [1:0] {
	Y,
	U,
	V
} plane_type;

typedef enum logic [2:0] {
	M2_WAIT,
	PLANE_SELECT,
	M2_LEAD_IN_1,
	M2_LEAD_IN_2,
	MEGA_STATE_1,
	MEGA_STATE_2,
	M2_LEAD_OUT_1,
	M2_LEAD_OUT_2
} M2_TOP_STATE_TYPE;

typedef enum logic [3:0] {
	WAIT_FETCH,
	DUMMYF_START_1,
	DUMMYF_START_2,
	DUMMYF_START_3,
	BIG_FETCH,
	DUMMYF_END_1,
	DUMMYF_END_2,
	DUMMYF_END_3,
	DUMMYF_END_4,
	DUMMYF_END_5,
	FS_BUFFER_STATE
} FETCH_STATE_TYPE;

typedef enum logic [3:0] {
	CT_WAIT,
	CT_DUMMY_IN,
	COMMON_1,
	CT_WRITE,
	CT_WRITE_2,
	CT_WRITE_LAST,
	CT_DUMMY_OUT,
	CT_BUFFER_STATE,
	CT_DUMMY_IN_2,
	CT_WRITE_BUFFER,
	CT_WRITE_LAST_BUFFER
} COMPUTE_T_STATE_TYPE;



typedef enum logic [5:0] {
	WAIT_CS,
	DUMMY_S_COMPUTE1,
	DUMMY_S_COMPUTE2,
	THREE_AT_A_TIME,
	SPECIAL_CASE,
	COMPLETE_S_SUM_COMMON,
	COMPLETE_S_SUM_SPECIAL,
	COMPLETE_S_WRITE1_SPECIAL,
	COMPLETE_S_WRITE1_COMMON,
	COMPLETE_S_WRITE2_COMMON,
	COMPLETE_S_WRITE3_COMMON,
	COMPLETE_S_WRITE_BUFFER,
	COMPLETE_S_WRITE_BUFFER0,
	CS_BUFFER_STATE_Y,
	CS_BUFFER_STATE_U,
	CS_BUFFER_STATE_V,
	COMPLETE_S_BUFFERCALC1COMMON,
	COMPLETE_S_BUFFERCALC1SPECIAL
} COMPUTE_S_STATE;



typedef enum logic [3:0] {
	WAIT_WRITE_S,
	DUMMY_WS_START_1,
	BIG_WS,
	DUMMY_WS_END_1,
	DUMMY_WS_END_2,
	WS_BUFFER_STATE,
	DUMMY_WS_START_2,
	WS_BUFFER_STATE1,
	WS_BUFFER_STATE2,
	WS_BUFFER_STATE3	
} WRITE_S_STATE_TYPE;





typedef enum logic [5:0] {
	WAIT_IDLE,
	LEAD_IN_1,
	LEAD_IN_2,
	LEAD_IN_3,
	LEAD_IN_4,
	LEAD_IN_5,
	LEAD_IN_6,
	LEAD_IN_7,
	LEAD_IN_8,
	LEAD_IN_9,
	LEAD_IN_10,
	LEAD_IN_11,
	LEAD_IN_12,
	LEAD_IN_13,
	LEAD_IN_14,
	LEAD_IN_15,
	LEAD_IN_16,
	LEAD_IN_17,
	LEAD_IN_18,
	LEAD_IN_19,
	LEAD_IN_20,
	COMMON_CASE_1,
	COMMON_CASE_2,
	COMMON_CASE_3,
	COMMON_CASE_4,
	COMMON_CASE_5,
	COMMON_CASE_6,
	COMMON_CASE_7,
	COMMON_CASE_8,
	LEAD_OUT_1,
	LEAD_OUT_2,
	LEAD_OUT_3,
	LEAD_OUT_4,
	LEAD_OUT_5,
	LEAD_OUT_6,
	LEAD_OUT_7,
	LEAD_OUT_8,
	LEAD_OUT_9,
	IDLE_WRITE_1,
	IDLE_WRITE_2,
	IDLE_WRITE_3,
	IDLE_BUFFER	
} MILESTONE_ONE_state_type;


parameter 
   VIEW_AREA_LEFT = 224,
   VIEW_AREA_RIGHT = 416,
   VIEW_AREA_TOP = 168,
   VIEW_AREA_BOTTOM = 312;

`define DEFINE_STATE 1
`endif

